server {
    listen 80;
    server_name 15.252.70.129;

    location /.well-known/acme-challenge/ {
        alias /var/www/certbot/.well-known/acme-challenge/;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name 15.252.70.129;

    ssl_certificate /etc/letsencrypt/live/15.252.70.129/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/15.252.70.129/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location /svc/api/ {
        proxy_pass http://backend:8000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
